

TITLE_KEYWORDS = {
    'Interplanetary': 4,
    'Supernova': 3,
    'Core-Collapse': 2,
    'Core': 1, # core is often found
    'Collapse': 1,
    'Explosion': 2,
    'Mechanism': 2,
    'Merger': 2,
    'Rotation': 1,
    'Two-Moment': 5,
    'Moment': 1, # moment is often found (momentum)
    'Ray-by-Ray': 5,
    'Multi-Dimensional': 3,
    'Three-Dimensional': 4,
    'Three': 1,
    'SASI': 4,
    'LESA': 5,
    'Neutrino': 5,
    'Flavor': 2,
    'Flavour': 2,
    'Oscillation': 2,
    'Transport': 4,
    'Simulation': 3,
    'Equation of State': 2,
    'Gravitational Wave': 1,
    'Nucleosynthesis': 1,
    'Massive': 1,
    'Star': 1,
}
AUTHORS = {
    'Janka': 5,
    'Couch': 4,
    'Connor': 5,  # O'Connor
    'Ott': 1, # Ott is often found
    'Abdikamalov': 2,
    'Sullivan': 2,
    'Burrows': 5,
    'Sumiyoshi': 4,
    'Skinner': 5,
    'Vartanyan': 5,
    'Dolence': 4,
    'Bollig': 4,
    'Ertl': 4,
    'Just': 5,
    'Obergaulinger': 4,
    'Andresen': 3,
    'Roberts': 5,
    'Radice': 4,
    'Tamborra': 3,
    'Kotake': 3,
    'Kuroda': 3,
    'Takiwaki': 3,
    'Nakamura': 3,
    'Takahashi': 3,
    'Nagakura': 3,
    'Mirizzi': 3,
    'Langer': 3,
    'Fischer': 3,
    'Heger': 2,
    'Woosley': 3,
    'Walk': 1,
    'Powell': 1,
    'Soker': 3,
}
